name: snakemake

description: Run Snakemake on the repository

branding:
  icon: git-pull-request
  color: green

inputs:
  directory:
    description: Working directory for the execution
    required: true
    default: .test
  snakefile:
    description: Snakefile containing the workflow description
    default: Snakefile
  args:
    description: Additional Snakemake arguments to use
    required: false
    default: ''
  stagein:
    description: Additional steps to prepare the workflow for execution
    required: false
    default: ''
  task:
    description: Whether to run Snakemake or to generate a container image specification.
    required: false
    default: 'run'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.snakefile }}
    - ${{ inputs.args }}
    - ${{ inputs.stagein }}
    - ${{ inputs.task }}
