name: snakemake

description: Run Snakemake on the repository

branding:
  icon: git-pull-request
  color: green

inputs:
  directory:
    description: Working directory for the execution
    required: true
    default: .test
  snakefile:
    description: Snakefile containing the workflow description
    default: Snakefile
  args:
    description: Additional Snakemake arguments to use
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.snakefile }}
    - ${{ inputs.args }}
